version: "3.7"
services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "6432:5432"
        networks:
            - backend
        restart: unless-stopped

volumes:
    postgres:

networks:
    backend:
        name: backend
        driver: bridge
